name: FreeBSD Build
env:
  DEBUG: napi:*
  APP_NAME: rollup

on:
  push:
    branches:
      - freebsd-support

jobs:
  build-freebsd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        settings:
          - name: freebsd
            architecture: x86-64
            version: '13.3'
            target: x86_64-unknown-freebsd
          - name: freebsd
            architecture: arm64
            version: '13.3'
            target: aarch64-unknown-freebsd
    name: Build ${{ matrix.settings.name }} ${{ matrix.settings.architecture }}
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: Build
        uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: ${{ matrix.settings.name }}
          architecture: ${{ matrix.settings.architecture }}
          version: ${{ matrix.settings.version }}
          cpu_count: 4
          memory: 8G
          run: |
            sudo pkg install -y node npm rust
            npm ci --ignore-scripts
            npm run build:napi -- --release --target ${{ matrix.settings.target }}
      - name: Upload napi artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: ${{ env.APP_NAME }}.*.node
          if-no-files-found: error
