name: Node CI

on: [push]

jobs:
  build:

    runs-on: windows-2019

    strategy:
      matrix:
        node: [ '10', '6' ]

    name: Node ${{ matrix.node }} - Windows
    steps:
    - name: Configure git line-breaks
      run: git config --global core.autocrlf false
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Configure Node version
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Check npm version
      run: IF ${{ matrix.node }} LSS 8 npm i npm@5 -g
    - name: Install dependencies
      run: npm ci --ignore-scripts
    - name: Run tests
      run: npm test
      env:
        CI: true
        WINDOWS: true
