name: Upload REPL artefacts
on:
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Build artefacts
        run: npm run build:cjs && npm run build:bootstrap
      - name: Upload ${{ github.event.number }}/rollup.browser.js to bucket
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --cache-control max-age=300,public
        env:
          FILE: dist/rollup.browser.js
          AWS_REGION: us-east-1
          S3_BUCKET: rollup-ci-artefacts
          S3_KEY: ${{ github.event.number }}/rollup.browser.js
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
